pipeline {
    agent any {
        stages {
            stage('checkout') {
                steps {
                    checkout scm
                }
            }
            stage('Validate openapi spec') {
                steps {
                    sh '''
                    redocly lint GP2/oas/api-oas.yaml
                    '''
                }
            }
        }
    }
}