pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('Validate openapi spec') {
            steps {
                sh '''
                redocly lint GP2/oas/api-oas.yaml
                '''
            }
        }
        stage('Generate kong config') {
            steps {
                sh '''
                python3 GP2/scripts/generate.py
                '''
            }
        }
        stage('Validate kong config') {
            steps {
                sh '''
                deck file validate GP2/generated/kong.yaml
                '''
            }
        }
    }
}